# Generated by Django 5.0.3 on 2024-04-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=50, unique=True)),
                ('FirstName', models.CharField(blank=True, max_length=50, null=True)),
                ('MiddleName', models.CharField(blank=True, max_length=50, null=True)),
                ('LastName', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('ContactNumber1', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('ContactNumber2', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
