# Generated by Django 5.0.3 on 2024-04-15 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_owners'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('PropertyID', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.TextField()),
                ('Price', models.FloatField()),
                ('AvailabilityStatus', models.BooleanField()),
                ('OwnerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.owners')),
            ],
        ),
    ]
