# Generated by Django 5.0.3 on 2024-04-15 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('LocationID', models.AutoField(primary_key=True, serialize=False)),
                ('Latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('Longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('StreetAddress', models.CharField(max_length=255)),
                ('StreetNumber', models.CharField(max_length=20)),
                ('LandNumber', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=100)),
                ('ZipCode', models.CharField(max_length=20)),
                ('Country', models.CharField(max_length=100)),
                ('PropertyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.property')),
            ],
        ),
    ]
