# Generated by Django 5.0.3 on 2024-04-16 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_propertyimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='OwnerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.user'),
        ),
        migrations.DeleteModel(
            name='Owners',
        ),
    ]
