# Generated by Django 5.0.3 on 2024-04-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_alter_propertyimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='img/'),
        ),
    ]
