# Generated by Django 5.0.3 on 2024-04-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
