# Generated by Django 5.0.3 on 2024-04-19 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_proposal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buys',
            name='Status',
            field=models.BooleanField(default=False),
        ),
    ]
