# Generated by Django 5.0.3 on 2024-04-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_alter_buys_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='LastName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
