# Generated by Django 5.0.3 on 2024-04-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0014_alter_user_lastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmpID', models.IntegerField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=255)),
                ('MiddleName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('ContactNumber1', models.BigIntegerField()),
                ('ContactNumber2', models.BigIntegerField()),
                ('Ratings', models.FloatField()),
                ('IsAvailable', models.BooleanField()),
            ],
        ),
    ]
