# Generated by Django 5.0.3 on 2024-04-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0015_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ContactNumber2',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='MiddleName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Ratings',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
