# Generated by Django 5.0.3 on 2024-04-20 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0016_alter_employee_contactnumber2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('ServiceID', models.IntegerField(primary_key=True, serialize=False)),
                ('ServiceName', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('Price', models.FloatField()),
                ('EmpID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.employee')),
            ],
        ),
    ]
