# Generated by Django 5.0.3 on 2024-04-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0018_services_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='EmpID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
