# Generated by Django 5.0.3 on 2024-04-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0019_alter_employee_empid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='ServiceID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
