# Generated by Django 5.0.3 on 2024-04-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0020_alter_services_serviceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='Price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
