# Generated by Django 5.0.3 on 2024-04-20 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0022_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='EmpID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.employee'),
        ),
    ]
