# Generated by Django 5.0.3 on 2024-04-20 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0025_remove_services_empid_services_employees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='Employees',
        ),
    ]
