# Generated by Django 5.0.3 on 2024-04-20 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0027_provides'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
