# Generated by Django 5.0.3 on 2024-04-25 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0029_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
